# Generated by Django 2.1.3 on 2018-11-14 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('revista', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('en_portada', models.BooleanField(default=False)),
                ('categoria', models.CharField(max_length=100)),
                ('imagen_destacada_uno', models.FileField(upload_to='articulos/uno/')),
                ('redactado_por', models.CharField(blank=True, default='Equipo MX OPPORTUNITY', max_length=300, null=True)),
                ('status', models.CharField(choices=[('Publicado', 'Publicado'), ('No Publicado', 'No publicado')], default='Publicado', max_length=50)),
                ('cuerpo', models.TextField()),
                ('imagen_destacada_dos', models.FileField(upload_to='articulos/dos/')),
                ('video_tipo', models.CharField(choices=[('youtube', 'youtube'), ('vimeo', 'vimeo'), ('sin video', 'sin video')], default='sin video', max_length=50)),
                ('urlvideo', models.URLField(blank=True, null=True)),
                ('llamada_accion', models.CharField(choices=[('Contactar', 'Contactar'), ('Visitar', 'Visitar'), ('Compar', 'Comprar'), ('Llamar', 'Llamar')], max_length=50)),
                ('imagen_llamada', models.FileField(upload_to='llamadas')),
                ('url_llamada', models.URLField()),
                ('cortesia_de', models.CharField(blank=True, max_length=300, null=True)),
                ('fecha_mostrada', models.DateField()),
                ('fecha_publicacion', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('origen_revista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='revista.Revista')),
            ],
        ),
    ]
