# Generated by Django 2.1.3 on 2018-11-22 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='imagen_destacada_dos',
            field=models.FileField(blank=True, null=True, upload_to='articulos/dos/'),
        ),
    ]
